/*
 * Creates an instance of FCKEditor for each textarea with a class attribute of 'rich'
 * If you need to make changes do not edit this file, make a copy (for example in
 * %project-dir%/web/js) and include your own copy in form template.
 */
window.onload = function()
{
  var els = document.getElementsByTagName("textarea");
  var re = new RegExp('\\brich\\b');
  for(var i=0; i < els.length; i++)
  {
    if(re.test(els[i].className))
    {
      var oFCKeditor = new FCKeditor(els[i].getAttribute('name'));
      //Change if FCKEditor is installed in a different path
      oFCKeditor.BasePath = "/js/fckeditor/" ;
      //Change if you use your own configuration file
      oFCKeditor.Config["CustomConfigurationsPath"] = "/lyMediaManagerPlugin/js/lymedia_fck_cfg.js";
      oFCKeditor.ReplaceTextarea();
    }
  }
}

