/*
 * FCKEditor Configuration file.
 * See http://docs.cksource.com/FCKeditor_2.x/Developers_Guide/Configuration_File
 * If you need to add more configuration options do not edit this file, make a
 * copy (for example in %project-dir%/web/js) then edit 'lymedia_fck_init.js' to
 * include your own copy.
 */

//Change the path below if lyMediaAsset module is enabled in an application different than 'backend'
FCKConfig.ImageBrowserURL = '/backend.php/ly_media_asset/icons?popup=1&editor=fck';

